/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class ndk1_Simple4 */

#ifndef _Included_ndk1_Simple4
#define _Included_ndk1_Simple4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk1_Simple4
 * Method:    callAddMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ndk1_Simple4_callAddMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
